DROP TABLE vehicles CASCADE CONSTRAINTS;
DROP TABLE races CASCADE CONSTRAINTS;

CREATE TABLE vehicles (
    id INTEGER,
    name VARCHAR2(20),
    vtype VARCHAR2(20),
    CONSTRAINT pkVehicle PRIMARY KEY(id)
);
CREATE TABLE races (
    vid1 INTEGER,
    vid2 INTEGER,
    time1 DATE,
    time2 DATE,
    CONSTRAINT fkVeh1 FOREIGN KEY(Vid1) REFERENCES vehicles(id),
    CONSTRAINT fkVeh2 FOREIGN KEY(Vid2) REFERENCES vehicles(id)
);

INSERT INTO vehicles VALUES(11,'Isetta','CAR');
INSERT INTO vehicles VALUES(22,'Ro 80','CAR');
INSERT INTO vehicles VALUES(33,'NSU Prinz','CAR');
INSERT INTO vehicles VALUES(44,'DS 50','BIKE');
INSERT INTO vehicles VALUES(55,'Puch Sissi','BIKE');
INSERT INTO vehicles VALUES(66,'Puch Maxi','BIKE');
INSERT INTO vehicles VALUES(77,'Kaefer 1200','CAR');
INSERT INTO vehicles VALUES(88,'Kaefer 1302','CAR');

INSERT INTO races VALUES(11,22,TO_DATE('05:44','MI:SS'),TO_DATE('03:44','MI:SS'));
INSERT INTO races VALUES(11,33,TO_DATE('05:21','MI:SS'),TO_DATE('04:44','MI:SS'));
INSERT INTO races VALUES(22,33,TO_DATE('03:33','MI:SS'),TO_DATE('03:44','MI:SS'));
INSERT INTO races VALUES(55,66,TO_DATE('13:33','MI:SS'),TO_DATE('23:44','MI:SS'));
INSERT INTO races VALUES(22,88,TO_DATE('13:33','MI:SS'),TO_DATE('13:32','MI:SS'));
INSERT INTO races VALUES(88,22,TO_DATE('13:55','MI:SS'),TO_DATE('13:55','MI:SS'));

COMMIT;